# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 16:49
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('coordinates', models.CharField(editable=False, max_length=256, primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantModel',
            fields=[
                ('uuid', models.CharField(db_index=True, default=api.models.make_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(blank=True, max_length=256, null=True)),
                ('restaurant_type', models.CharField(blank=True, max_length=256, null=True)),
                ('phone', models.CharField(blank=True, max_length=256, null=True)),
                ('location', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
